### ISSUE TITLE
Are the split points correct?

### ISSUE THREAD

**Issue by probonopd** [BobanSpasic/MDX_PerfConv#11]
Are the split points correct? E.g., in `Sample&Hold(2F`, the middle C should probably be the main voice rather than the arpeggiated voice? I noticed the same for multiple of the split voices.

**Comment by BobanSpasic** [comment]
I don't know, we need a real DX7II to compare.
I've taken the split point to be the last key of the lower voice.
Do you think the split point should be the first key of the higher voice?

**Comment by probonopd** [comment]
Yes, I think so. Middle C shold be the first key of the upper voice. For most of them, at least. It actually differs depending on what is coded in the Yamaha performances (at least in the TX5 ones, so probably also for the other performance types).

**Comment by BobanSpasic** [comment]
Next commit will contain the correction

**Comment by BobanSpasic** [comment]
Fixed

**Comment by probonopd** [comment]
Thanks 👍 
Don't forget to `git push` so that the automated build produces the new conversions.

**Comment by BobanSpasic** [comment]
In the fact, the changes are already committed, and the conversions are built, but it seems that I've got another problem with output file names. It works fine on Windows, but not here with build-bot. That's why I said it is not ready.
