### ISSUE TITLE
Performances with references to ROM voices

### ISSUE THREAD

**Issue by BobanSpasic** [BobanSpasic/MDX_PerfConv#12]
I need to re-write the code because of DX7II and TX802 performances that are using ROM voices.
I also need to provide the ROM voices with the executable, in order to complete this.

**Comment by probonopd** [comment]
As for the DX7IIfd:

https://yamahablackboxes.com/collection/yamaha-dx7ii-fd-synthesizer/patches/ seems to have everything.

Aren't `dx7iifdvoice32.syx` and `dx7iifdvoice64.syx` the ROM voices?

**Comment by probonopd** [comment]
Isn't this doing the job?

```
wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice32.syx"
wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice64.syx"
wget -q "https://yamahablackboxes.com/patches/dx7ii/performances/dx7iifdperf.syx"
bin/Linux/MDX_PerfConv -c -a dx7iifdvoice32.syx -b dx7iifdvoice64.syx -p dx7iifdperf.syx
wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice32b.syx"
wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice64b.syx"
wget -q "https://yamahablackboxes.com/patches/dx7ii/performances/dx7iifdperfb.syx"
bin/Linux/MDX_PerfConv -c -n 33 -a dx7iifdvoice32b.syx -b dx7iifdvoice64b.syx -p dx7iifdperfb.syx
```

**Comment by BobanSpasic** [comment]
These patches on Yamaha Black Boxes are unusable. They are striped down to just VMEM. Usable on DX7 (mark 1), but not on a real DX7II. I already have the right files for DX7II: https://github.com/BobanSpasic/MDX_PerfConv/tree/main/Test_files/DX7IIFD_Factory  
 The missing ones were the voices 65 to 128 from TX802, with AMEM included.

**Comment by BobanSpasic** [comment]
Reading the manuals again and again...  
DX7II does not have ROM voices. It has Internal (64 voices) and Cartridge (64 voices). Internal can be overwritten with custom voices.
TX802 on the other hand has Internal (64 voices), Cartridge (64 voices), Preset A (64 voices) and Preset B (64 voices).
Preset A and Preset B are ROM voices (can't be overwritten).

As for the Cartridges - it can contain more than one bank (voice + corresponding performances), but you use just one at the time.

Program change over MIDI:
000 - 063 - Internal
064 - 127 - Cartridge
128 - 191 - Preset A (just TX802)
192 - 255 - Preset B (just TX802)

**Comment by BobanSpasic** [comment]
Commited

**Comment by probonopd** [comment]
Currently the `TX802_Factory` folder in the generated performances.zip is empty - do you know why?

**Comment by probonopd** [comment]
Currently the TX802 performances say `Origin=Conversion from DX7II Voices` - is this true for all of them?

**Comment by BobanSpasic** [comment]
TX802 Factory directory isn't included in the bat/sh files because it wasn't complete. I didn't update the scripts in bat/sh files.
It isn't the only directory that isn't processed. It is on my ToDo list.

TX802 voice banks are DX7II voice banks. Just the performance files are different.
