### ISSUE TITLE
Where does the converted performance ini get saved?

### ISSUE THREAD

**Issue by probonopd** [BobanSpasic/MDX_PerfConv#3]
When I do

```
        wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice32.syx"
        wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice64.syx"
        wget -q "https://yamahablackboxes.com/patches/dx7ii/performances/dx7iifdperf.syx"
        bin/Linux/MDX_PerfConv --info -a dx7iifdvoice32.syx -b dx7iifdvoice64.syx -p dx7iifdperf.syx
        bin/Linux/MDX_PerfConv -c -a dx7iifdvoice32.syx -b dx7iifdvoice64.syx -p dx7iifdperf.syx
        ls -lh
```

then I see this, but no `.ini` file:

```
X7/DX9 Voice Bank - VMEM at position 6
Calculated data size: 4096
Real data size: 4096
Checksum match
DX7/DX9 Voice Bank - VMEM at position 6
Calculated data size: 4096
Real data size: 4096
Checksum match
DX7II PMEM at position 6
Calculated data size: 1642
Real data size: 1642
Checksum match
total 84M
-rw-r--r-- 1 runner docker  25K Nov 12 10:39 COPYING.LGPL.txt
-rw-r--r-- 1 runner docker 1005 Nov 12 10:39 COPYING.modifiedLGPL.txt
-rw-r--r-- 1 runner docker 4.9K Nov 12 10:39 MDX_PerfConv.lpi
-rw-r--r-- 1 runner docker 9.0K Nov 12 10:39 MDX_PerfConv.lpr
-rw-r--r-- 1 runner docker  15K Nov 12 10:39 MDX_PerfConv.lps
-rw-r--r-- 1 runner docker  860 Nov 12 10:39 MDX_PerfConv.res
-rw-r--r-- 1 runner docker 1.6K Nov 12 10:39 README.md
drwxr-xr-x 3 runner docker 4.0K Nov 12 10:39 bin
-rw-r--r-- 1 runner docker  215 Nov 12 10:39 compile.bat
-rw-r--r-- 1 runner docker  195 Nov 12 10:39 compile.sh
-rw-r--r-- 1 runner docker 1.7K Nov 12 10:39 dx7iifdperf.syx
-rw-r--r-- 1 runner docker 4.1K Nov 12 10:39 dx7iifdvoice32.syx
-rw-r--r-- 1 runner docker 4.1K Nov 12 10:39 dx7iifdvoice64.syx
drwxr-xr-x 2 runner docker 4.0K Nov 12 10:39 fpc-3.2.2.x86_64-linux
-rw-r--r-- 1 runner docker  83M May 19  2021 fpc-3.2.2.x86_64-linux.tar
drwxr-xr-x 3 runner docker 4.0K Nov 12 10:39 lib
drwxr-xr-x 2 runner docker 4.0K Nov 12 10:39 units
-rw-r--r-- 1 runner docker  25K Nov 12 10:39 untConverter.pas
-rw-r--r-- 1 runner docker 3.4K Nov 12 10:39 untDispatcher.pas
```

https://github.com/probonopd/MDX_PerfConv/actions/runs/6840186012/job/18599167257#step:3:227

**Comment by BobanSpasic** [comment]
That's just the output of the --info. Output from -c should show the voice and performance names.
If there is no path in the syx filenames, the current working directory will be used for output, and this will be written in the output of -c parameter.
Somehow, the -c isn't executed at all.

**Comment by probonopd** [comment]
> Somehow, the -c isn't executed at all.

Does it work for you when you do the same?

**Comment by BobanSpasic** [comment]
Nope. Same results like yours. I'll check it right now. I guess it has to do with finding the paths to the files.

**Comment by BobanSpasic** [comment]
Found the culprit - the voice syx files.
The voice banks are in DX7 format (VMEM, 4kb). The converter expects DX7II format (VMEM+AMEM, some 5kb) and it terminates because AMEM is not found.
Dunno if it is worth to convert without AMEM. AMEM contains the controller settings (ModWheel, BreathController etc.), portamento settings, poly/mono...
We are taking at the moment just the Single/Dual/Split, DualDetune and SplitPoint from Performance.

**Comment by probonopd** [comment]
I guess we want to use all of these. For now, I'd say let's convert them but comment them out with

```
# TODO: Parameter=Value
```

in the converted ini file. This way, we know what we still need to implement in MiniDexed.

**Comment by BobanSpasic** [comment]
It should work now. Testbed is in the "test" directory.
It does not make much sense, because the performances 05, 22 and 26 are single voices, and without AMEM parameters they are not different to the source voices.

**Comment by probonopd** [comment]
Is there a way to make subsequent runs use increasing integers for numbering the files?

https://github.com/probonopd/MDX_PerfConv/releases currently has two 000001_...

```
        wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice32.syx"
        wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice64.syx"
        wget -q "https://yamahablackboxes.com/patches/dx7ii/performances/dx7iifdperf.syx"
        bin/Linux/MDX_PerfConv --info -a dx7iifdvoice32.syx -b dx7iifdvoice64.syx -p dx7iifdperf.syx
        bin/Linux/MDX_PerfConv -c -a dx7iifdvoice32.syx -b dx7iifdvoice64.syx -p dx7iifdperf.syx
        wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice32b.syx"
        wget -q "https://yamahablackboxes.com/patches/dx7ii/voices/dx7iifdvoice64b.syx"
        wget -q "https://yamahablackboxes.com/patches/dx7ii/performances/dx7iifdperfb.syx"
        bin/Linux/MDX_PerfConv --info -a dx7iifdvoice32b.syx -b dx7iifdvoice64b.syx -p dx7iifdperfb.syx
        bin/Linux/MDX_PerfConv -c -a dx7iifdvoice32b.syx -b dx7iifdvoice64b.syx -p dx7iifdperfb.syx
```

Maybe an `-n` argument to set the first number, with `1` being the default if the parameter is omitted?

**Comment by BobanSpasic** [comment]
Could you give a try to the last commit?
I am in a hurry, can't test myself for the next 2-3 hours

**Comment by probonopd** [comment]
Thanks, it works!
